### ISSUE TITLE
How to limit the output mp4 file zsize?

### ISSUE THREAD

**Issue by luisxiaomai** [WPO-Foundation/xrecord#2]
Hi @pmeenan ,

Thanks for your useful tool that can help record iOS device.

But I found that the output mp4 file is tool large(40s=50MB), if there is a way to limit the output file size within the commandline parameter?

Thanks
Luis

**Comment by pmeenan** [comment]
Sorry, no.  Right now it is hard-coded to record at the highest quality: https://github.com/WPO-Foundation/xrecord/blob/master/xrecord/capture.swift#L22

It shouldn't be too hard to add a command-line setting that let you pick the medium or low quality settings though you'll sacrifice the quality of the actual recording: https://github.com/WPO-Foundation/xrecord/blob/master/xrecord/capture.swift#L22

The size of the video is largely going to depend on what is happening on the screen (the more it changes the bigger the files).  Setting a file size limit would just truncate the video earlier so I'm assuming that's not what you want.

For the best control over it I recommend using ffmpeg to post-process the video after it was recorded.  You could resize it to be lower resolution and adjust the quality with a lot more control.

I'm happy to add the 3-level quality settings to the command-line if that would help but I don't know if that will give you the control you're looking for.

**Comment by luisxiaomai** [comment]
Thanks, I tried the ffpmeg to compress the video before you instrumention. It works fine.

Look forward your new innovation.

**Comment by pmeenan** [comment]
There is now a --quality setting that lets you specify low, medium, high or photo.  It may still not give you the exact quality/size you are looking for and ffmpeg still gives you a lot more knobs but it may help.
