### ISSUE TITLE
device discover 

### ISSUE THREAD

**Issue by Noiled** [WPO-Foundation/xrecord#3]
@pmeenan 
when I typed command as you said "./xrecord --quicktime --list" , I can find my iphone device (already connected to my mac), only when I opened quicktime app.

**Comment by pmeenan** [comment]
can you pass --debug as a flag as well and provide the output?

**Comment by pmeenan** [comment]
Oh, and did it find the device without quicktime running manually?  Not sure what "only when I opened quicktime app" refers to.

I've seen some issues with iOS 9 and El Capitan where there are timing issues where the device doesn't show up immediately after starting quicktime which might be causing the issues you are seeing (if you're getting a device not found message).  I'm planning on working on that today.

**Comment by Noiled** [comment]
@pmeenan  appreciate your prompt  reply 
   Oh, and did it find the device without quicktime running manually ?    NO
I can find  my device only when I lanuch quicktime

**Comment by TitouanVanBelle** [comment]
@Noiled @pmeenan Was this issue resolved somehow? I also seem to have the same behaviour

```
$ instruments -s devices
tito (11.0) [73363b7406eeb064e2d5ddec2667315d6110a16e]
```

```
$ xrecord --quicktime --list
Available capture devices:
AppleHDAEngineInput:1B,0,1,0:1: Built-in Microphone
CC26311ECFEG1HNBX: FaceTime HD Camera
```

Now when I open Quicktime, select Movie Recording and select my device I get the following

```
$ xrecord --quicktime --list
Available capture devices:
AppleHDAEngineInput:1B,0,1,0:1: Built-in Microphone
CC26311ECFEG1HNBX: FaceTime HD Camera
73363b7406eeb064e2d5ddec2667315d6110a16e: tito
```
