### ISSUE TITLE
Support latest xcode 8 + iOS 9, iOS10

### ISSUE THREAD

**Issue by luisxiaomai** [WPO-Foundation/xrecord#5]
Hi,

This tool seems can't find iOS9 or iOS10 related simulator or device?
Can you help on this?

Thanks
Luis

**Comment by pmeenan** [comment]
The tool only works with devices, not simulators and should be independent of XCode.

If you open Quicktime and start a new recording, does the device you want to record from show up in the list?  That should be functionally equivalent to what XRecord is doing.

**Comment by luisxiaomai** [comment]
@pmeenan thanks for you explanation. I retested and it's fine for device.
But on the other hand, can you support iOS simulator or recommend other tool which can record iOS simulator?

**Comment by pmeenan** [comment]
Sorry, recording from simulator isn't a goal for this project.  A lot of existing tools do it by recording the simulator window in OSX.
